/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class GameModes extends javax.swing.JPanel {

    /**
     * Creates new form GameModes
     */
    public GameModes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        limitedTimeLabel = new javax.swing.JButton();
        limitedArrowLabel = new javax.swing.JButton();
        limitedMissLabel = new javax.swing.JButton();
        adventureLabel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("AR BLANCA", 1, 48)); // NOI18N
        jLabel1.setText("Game Modes");

        limitedTimeLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        limitedTimeLabel.setText("Limited Time");
        limitedTimeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitedTimeLabelActionPerformed(evt);
            }
        });

        limitedArrowLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        limitedArrowLabel.setText("Limited Arrow");
        limitedArrowLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitedArrowLabelActionPerformed(evt);
            }
        });

        limitedMissLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        limitedMissLabel.setText("Limited Miss");
        limitedMissLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitedMissLabelActionPerformed(evt);
            }
        });

        adventureLabel.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        adventureLabel.setText("Adventure");
        adventureLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adventureLabelActionPerformed(evt);
            }
        });

        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(217, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limitedMissLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limitedTimeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(198, 198, 198)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(adventureLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(limitedArrowLabel))
                .addGap(234, 234, 234))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limitedTimeLabel)
                    .addComponent(limitedArrowLabel))
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limitedMissLabel)
                    .addComponent(adventureLabel))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limitedArrowLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitedArrowLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitedArrowLabelActionPerformed

    private void limitedTimeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitedTimeLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitedTimeLabelActionPerformed

    private void adventureLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adventureLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adventureLabelActionPerformed

    private void limitedMissLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitedMissLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_limitedMissLabelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adventureLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limitedArrowLabel;
    private javax.swing.JButton limitedMissLabel;
    private javax.swing.JButton limitedTimeLabel;
    // End of variables declaration//GEN-END:variables
}
