/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        header1 = new javax.swing.JLabel();
        play1 = new javax.swing.JButton();
        playVideo1 = new javax.swing.JButton();
        collectedInfo1 = new javax.swing.JButton();
        credits1 = new javax.swing.JButton();
        scoreboards1 = new javax.swing.JButton();
        exit1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 255));

        jPanel2.setBackground(new java.awt.Color(215, 14, 14));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.yellow, null, null));

        header1.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        header1.setText("Apollon");

        play1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        play1.setText("Play");
        play1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                play1ActionPerformed(evt);
            }
        });

        playVideo1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        playVideo1.setText("How to Play");
        playVideo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playVideo1ActionPerformed(evt);
            }
        });

        collectedInfo1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        collectedInfo1.setText("Collected Informations");

        credits1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        credits1.setText("Credits");
        credits1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credits1ActionPerformed(evt);
            }
        });

        scoreboards1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        scoreboards1.setText("Scoreboards");
        scoreboards1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreboards1ActionPerformed(evt);
            }
        });

        exit1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        exit1.setText("EXIT");
        exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(credits1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(play1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playVideo1)
                    .addComponent(scoreboards1))
                .addGap(147, 147, 147))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(exit1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(collectedInfo1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(header1)))
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(header1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(play1)
                    .addComponent(playVideo1))
                .addGap(57, 57, 57)
                .addComponent(collectedInfo1)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(credits1)
                    .addComponent(scoreboards1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(exit1)
                .addGap(119, 119, 119))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void play1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_play1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_play1ActionPerformed

    private void playVideo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playVideo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playVideo1ActionPerformed

    private void credits1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credits1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_credits1ActionPerformed

    private void scoreboards1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreboards1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scoreboards1ActionPerformed

    private void exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit1ActionPerformed
         System.exit(WIDTH);
    }//GEN-LAST:event_exit1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton collectedInfo1;
    private javax.swing.JButton credits1;
    private javax.swing.JButton exit1;
    private javax.swing.JLabel header1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton play1;
    private javax.swing.JButton playVideo1;
    private javax.swing.JButton scoreboards1;
    // End of variables declaration//GEN-END:variables
}
